# Site settings
title: "Fonobot - M&aacute;rketing telef&oacute;nico al alcance de todos"
email: info@fonobot.com
description: > # this means to ignore newlines until "baseurl:"
  Fonobot es un sistema on-line de m치rketing telef칩nico al alcance de todos.
  Le permite realizar llamadas telef칩nicas de m치rketing de manera simple y efectiva,
  sin conocimientos previos, y a un costo accesible.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.fonobot.com" # the base hostname & protocol for your site
twitter_username: fonobot
github_username:  fonobot

# Build settings
markdown: kramdown

# Para prueba local comentar "exclude" y poner "production" en false
exclude: [ local ]
production: true
